version: '3.7'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-cyrelas:/var/lib/mysql

networks:
  default:
    name: board

volumes:
  mysql-cyrelas: